a='Chirag'
print('string',end=' ')
print(a)
print('string as title',end='  ')
print(a.title())
print('count ir in string',end=' ')
print(a.count('ir'))
print('string in lowercase',end=' ')
print(a.lower())
print('swapcase of string',end=' ')
print(a.swapcase())
